name: "Caretaker Action"
author: "TGWolf"
description: "A tool to run caretaker to generate changelogs."

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  output-file:  # id of input
    description: 'The name of the changelog file'
    required: true
    default: 'CHANGELOG.md'

runs:
  using: 'docker'
  image: Dockerfile

branding:
  icon: 'activity'
  color: 'white'
