name: "Caretaker Action"
author: "TGWolf"
description: "A tool to run caretaker to generate changelogs."

inputs:
  git-push-user-name:
    description: If empty the name of the GitHub Actions bot will be used (i.e. `github-actions[bot]`)
    required: false
    default: ""
  git-push-user-email:
    description: If empty the no-reply email of the GitHub Actions bot will be used (i.e. `github-actions[bot]@users.noreply.github.com`)
    required: false
    default: ""
  git-commit-message:
    description: Commit message
    required: false
    default: "caretaker-action: automated action"
  output-file:
    description: 'The name of the changelog file'
    required: true
    default: 'CHANGELOG.md'
  args:
    description: 'Additional arguments to pass to the command (see [full documentation](https://github.com/terraform-docs/terraform-docs/tree/master/docs))'
    required: false
    default: ""

runs:
  using: 'docker'
  image: Dockerfile
  env:
    INPUT_GIT_PUSH_USER_NAME: ${{ inputs.git-push-user-name }}
    INPUT_GIT_PUSH_USER_EMAIL: ${{ inputs.git-push-user-email }}
INPUT_GIT_COMMIT_MESSAGE: ${{ inputs.git-commit-message }}
    OUTPUT_FILE: ${{ inputs.output-file }}
    ARGS: ${{ inputs.args }}

branding:
  icon: 'activity'
  color: 'white'
