name: "Caretaker Action"
author: "TGWolf"
description: "A tool to run caretaker to generate changelogs."

inputs:
  output-file:  # id of input
    description: 'The name of the changelog file'
    required: true
    default: 'CHANGELOG.md'

runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.output-file }}
