name: "Caretaker Action"
author: "TGWolf"
description: "A tool to run caretaker to generate changelogs."

inputs:
  output:
    description: 'The name of the changelog file'
    required: true
    default: 'CHANGELOG.md'
  args:
    description: 'Additional arguments to pass to the command (see [full documentation](https://github.com/terraform-docs/terraform-docs/tree/master/docs))'
    required: false
    default: ""

runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.output }}
    - ${{ inputs.args }}

branding:
  icon: 'activity'
  color: 'white'
