name: Caretaker
on: [push]

#
# Needs to be updted on a release too
#

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Caretaker
    steps:
      - name: Check our repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Caretaker
        id: caretaker
        uses: ActionsToolbox/caretaker-action@master
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-push-user-email: 'caretaker-bot@wolfsoftware.com'
