name: Caretaker
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Caretaker
    steps:
      - name: Check our repo
        uses: actions/checkout@v3
      - name: Caretaker
        id: caretaker
        uses: ActionsToolbox/caretaker-action@master
        with:
          args: '-a -b more -c'
