name: Caretaker
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Caretaker
    steps:
      - name: Caretaker
        id: caretaker
        uses: ActionsToolbox/caretaker-action@master
